server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # server-addr: 192.168.174.129:1111 #换为nginx的端口，做集群
        server-addr: 127.0.0.1:8848 #配置Nacos地址
managemen:
  endpoints:
    web:
      exposure:
        include: '*'