server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  #hostname: localhost   #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不需要向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务条例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
      #设置与Eureka Server交互的地址查询服务和注册中心都需要依赖这个地址
      #http://${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #enable-self-preservation: false
    #关闭自我保护机制